### ISSUE TITLE
Hi MANLIKETJB can you make this script whit qb-menu 

### ISSUE THREAD

**Issue by Temouchenty** [Manliketjb/Manliketjb#1]
https://github.com/OxGhali/qb-storagelockers

**Comment by Manliketjb** [comment]
> https://github.com/OxGhali/qb-storagelockers

it already does... exports['qb-menu']:openMenu is what it uses

**Comment by Manliketjb** [comment]
also isn't this a paid resource?

**Comment by Temouchenty** [comment]
no before this one he was made with nh-context and i tried to make it with qb-menu and his not working and yes this is a paid resource from shanks

**Comment by Manliketjb** [comment]
> no before this one he was made with nh-context and i tried to make it with qb-menu and his not working and yes this is a paid resource

i would ask the creator if they can make a qb-menu version... i don't touch anyone paid resource... i would also delete it off github because it's now a "leak"... its a paid resource and you've uploaded it to a site that anyone can freely download it from (whether is works or not)

**Comment by Temouchenty** [comment]
okay i will delete it and if the owner say yes just tell me to send it to you

**Comment by Manliketjb** [comment]
> okay i will delete it and if the owner say yes just tell me to send it to you

if the owner says its ok the discord me and i will see what i can do but i'm still new to qb-menu so don't expect to much --- ManLikeTJB#4518

**Comment by Temouchenty** [comment]
okay no problem and i sent you an invitation on discord .. thank you bro
